### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by kmehkeri** [hound-search/hound#416]
I am attempting to index large number of repositories and I hit "Too many open files" error. I tried to increase OS limit - currently it's at 1000000 globally as confirmed by `ulimit -a` - but still after indexing ca. 1000 repos all the further git calls fail and I get something like this in the logs:

```
Mar 20 14:34:44 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:34:44 Searcher started for <repo_name>
Mar 20 14:34:44 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:34:44 fork/exec /usr/bin/git: too many open files
Mar 20 14:34:44 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:34:44 Failed to git show remote info /root/hound/db/vcs-b4c3db480cd3d6a9d48b03b7c8d6e4885fdeefaa, see output below
Mar 20 14:34:44 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: Continuing...
Mar 20 14:34:44 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:34:44 could not determine target ref in /root/hound/db/vcs-b4c3db480cd3d6a9d48b03b7c8d6e4885fdeefaa. Will fall back to default ref master
Mar 20 14:35:07 0bbdb7b7-c643-4732-8515-9c619e906bb7 systemd-journald[745286]: Suppressed 1462 messages from houndd.service
Mar 20 14:35:07 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:35:07 merge 0 files + mem
Mar 20 14:35:07 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:35:07 6908580 data bytes, 2247555 index bytes
Mar 20 14:35:08 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:35:08 merge 0 files + mem
Mar 20 14:35:08 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:35:08 107605 data bytes, 168334 index bytes
Mar 20 14:36:27 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:36:27 merge 0 files + mem
Mar 20 14:36:27 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:36:27 247226 data bytes, 237010 index bytes
Mar 20 14:36:32 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: 2022/03/20 14:36:32 openfdat /root/hound/db/idx-1174b9e9542d0642/raw/<path>: too many open files
Mar 20 14:36:32 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: panic: openfdat /root/hound/db/idx-1174b9e9542d0642/raw/<path>: too many open files
Mar 20 14:36:32 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: goroutine 1 [running]:
Mar 20 14:36:32 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: log.Panic({0xc0007edee8, 0xc0001f3ef8, 0x1})
Mar 20 14:36:32 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]:         /usr/local/go/src/log/log.go:354 +0x65
Mar 20 14:36:32 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]: main.main()
Mar 20 14:36:32 0bbdb7b7-c643-4732-8515-9c619e906bb7 houndd[755264]:         /root/go/pkg/mod/github.com/hound-search/hound@v0.4.0/cmds/houndd/main.go:156 +0x32b
```

Smaller number of repos (up to hundreds) are indexing fine. OS it runs on is Ubuntu 20.04 (I'll later try to setup the same on different OS).

**Comment by kmehkeri** [comment]
It's the same with CentOS 7.

Browsing issues I noticed this was already raised (quite a long time ago) in #139, so it's a duplicate, but I just wanted to mention that that issue is still valid.

**Comment by salemhilal** [comment]
@kmehkeri thank you for reporting this! Yeah, it is likely that we keep file handles around after indexing. We may want to see what we can do about closing handlers that aren't actively in use, but thousands of repos is certainly a lot of them. I'm gonna close this issue, but feel free to add additional comments either here or to the original issue.
